wandb_version: 1

train_file:
  desc: null
  value: data/ptb_20231129-train.pkl
val_file:
  desc: null
  value: data/ptb_20231129-val.pkl
ckpt_path:
  desc: null
  value: ''
w_dim:
  desc: null
  value: 380
num_layers:
  desc: null
  value: 12
dropout:
  desc: null
  value: 0.4
n_head:
  desc: null
  value: 10
d_head:
  desc: null
  value: 30
d_inner:
  desc: null
  value: 900
dropoutatt:
  desc: null
  value: 0.2
q_dim:
  desc: null
  value: 300
count_eos_ppl:
  desc: null
  value: 0
save_path:
  desc: null
  value: /ckpt/utg_ckpt_240103_1.pt
num_epochs:
  desc: null
  value: 18
warmup_epochs:
  desc: null
  value: 8
mode:
  desc: null
  value: unsupervised
eval_samples:
  desc: null
  value: 3
samples:
  desc: null
  value: 5
lr:
  desc: null
  value: 5.0e-05
q_lr:
  desc: null
  value: 0.0001
lr_decay:
  desc: null
  value: 0.8
kl_cost_annealing_warmup:
  desc: null
  value: 1.2
kl_pen_max:
  desc: null
  value: 0.8
train_q_epochs:
  desc: null
  value: 2
param_init:
  desc: null
  value: 0.1
max_grad_norm:
  desc: null
  value: 5
q_max_grad_norm:
  desc: null
  value: 1
gpu:
  desc: null
  value: 0
seed:
  desc: null
  value: 3407
print_every:
  desc: null
  value: 500
wandb:
  desc: null
  value: true
wandb_entity:
  desc: null
  value: itsuitsuki
run_name:
  desc: null
  value: utg20240225
wandb_key:
  desc: null
  value: 475897693adc3ae7b647e6010441cc105263892c
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1708888556.557575
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 1
      - 13
      - 16
      - 23
      4: 3.10.13
      5: 0.16.1
      8:
      - 2
      - 5
      13: linux-x86_64
